### ISSUE TITLE
Barrage of PHP Deprecated errors?

### ISSUE THREAD

**Issue by jsaern** [nrwtaylor/stack-agent-thing#2]
Hi!
While making the jump to Ubuntu 22 LTS, I also updated to php8.2.  My hypothesis:  you already upgraded over the last two years developing.  

The `agent` reports an endless stream of PHP deprecated errors until `fish` kills it.  

Console messages:
[20231001-r2-5-msg_deprecated.log.gz](https://github.com/nrwtaylor/stack-agent-thing/files/12778550/20231001-r2-5-msg_deprecated.log.gz)

Error messages:
[20231001-r2-5-err_deprecated.log.gz](https://github.com/nrwtaylor/stack-agent-thing/files/12778552/20231001-r2-5-err_deprecated.log.gz)

Latest pull report:
[20231001-r2-5-longwait.log](https://github.com/nrwtaylor/stack-agent-thing/files/12778551/20231001-r2-5-longwait.log)

**Comment by jsaern** [comment]
Semi-related - the Makefile seemed to work getting everything pulled together, except the version of PHP and getting the database options correct on the new Ubuntu instance.

**Comment by jsaern** [comment]
I haven't started running the database on the new version of Ubuntu, yet.

**Comment by jsaern** [comment]
Using the `dev` branch solves the PHP-deprecated errors.  

I do see a stream of code outputs, though.  Looks like I need to set up MongoDB to take full advantage of the cleaned-up messages?


[20231014-R2-2-results_mongodb.log](https://github.com/nrwtaylor/stack-agent-thing/files/12908370/20231014-R2-2-results_mongodb.log)
[20231014-R2-2-output_mongodb.log](https://github.com/nrwtaylor/stack-agent-thing/files/12908371/20231014-R2-2-output_mongodb.log)

**Comment by jsaern** [comment]
@nrwtaylor ? 
How tricky would you rate setting up MongoDB for Stackr?  
My first hypothesis is that structuring it the way we set up MqSQL is correct for the latest Stackr.

**Comment by jsaern** [comment]
@nrwtaylor ?
How risky would you rate using Dev rather than Main?
Appreciated invitation for December.

**Comment by jsaern** [comment]
Updated vendors using Composer and only have a few errors now.  

```
jsae@echo1 /v/w/s/vendor (master) [1]> agent ping
PHP Warning:  require(/var/www/stackr.test/vendor/composer/../guzzlehttp/psr7/src/functions_include.php): Failed to open stream: No such file or directory in /var/www/stackr.test/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/stackr.test/vendor/composer/../guzzlehttp/psr7/src/functions_include.php' (include_path='.:/usr/share/php') in /var/www/stackr.test/vendor/composer/autoload_real.php:66
Stack trace:
#0 /var/www/stackr.test/vendor/composer/autoload_real.php(56): composerRequire2fb5367ec0bc620f726cdfa83b0b4fe7()
#1 /var/www/stackr.test/vendor/autoload.php(7): ComposerAutoloaderInit2fb5367ec0bc620f726cdfa83b0b4fe7::getLoader()
#2 /var/www/stackr.test/agent(4): require('...')
#3 {main}
  thrown in /var/www/stackr.test/vendor/composer/autoload_real.php on line 66
jsae@echo1 /v/w/s/vendor (master) [255]> 
```

**Comment by jsaern** [comment]
Noticed `guzzlehttp`.

Installing it didn't fix the error.  

https://docs.guzzlephp.org/en/stable/overview.html#installation
